name: Build and deploy static site to Azure Web App - Fitness

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: nchikhim/UCCD2323_P8P9G50

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Fitness'
          slot-name: 'Production'
          package: 'nchikhim/UCCD2323_P8P9G50'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
